---

galaxy_info:
  author: kosssi
  description: Manages apt and executes apt-get update to ensure the local APT package cache is up to date.
  min_ansible_version: 1.4
  license: MIT
  platforms:
  - name: Ubuntu
    versions:
    - all
  categories:
  - system
